
services:
  - type: web
    name: zarzadzanie-plus
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: ""
      - key: DB_NAME
        value: zarzadzanie_plus
